### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by A-xis** [Diti/shadinfo#1]
Please, can you add a readme for random people like me? :D

**Comment by Diti** [comment]
Hello! I just made this project “easier” to install (you still need a recent version of Go, though), use (`-bind` and `-template` flags), and **finished explaining all of that in 04037cd.**

Keep in mind this is (still) a personal project for now, and (still) in beta—I still haven’t written everything I want to use.

If you plan on using this project as well, feel free to open new issues! 😃

**Comment by A-xis** [comment]
Thank you
